export enum BillStatus {
  INTRODUCED = 'INTRODUCED',
  IN_COMMITTEE = 'IN_COMMITTEE',
  PASSED_COMMITTEE = 'PASSED_COMMITTEE',
  FLOOR_VOTE = 'FLOOR_VOTE',
  PASSED = 'PASSED',
  FAILED = 'FAILED',
  SIGNED = 'SIGNED',
  VETOED = 'VETOED',
  ENACTED = 'ENACTED'
}

export enum BillType {
  HOUSE_BILL = 'HOUSE_BILL',
  SENATE_BILL = 'SENATE_BILL',
  JOINT_RESOLUTION = 'JOINT_RESOLUTION',
  CONCURRENT_RESOLUTION = 'CONCURRENT_RESOLUTION'
}

export enum VoteResult {
  PASSED = 'PASSED',
  FAILED = 'FAILED',
  NO_QUORUM = 'NO_QUORUM',
  POSTPONED = 'POSTPONED'
}

export enum ActionType {
  INTRODUCTION = 'INTRODUCTION',
  COMMITTEE_REFERRAL = 'COMMITTEE_REFERRAL',
  COMMITTEE_HEARING = 'COMMITTEE_HEARING',
  COMMITTEE_VOTE = 'COMMITTEE_VOTE',
  FLOOR_READING = 'FLOOR_READING',
  FLOOR_VOTE = 'FLOOR_VOTE',
  AMENDMENT = 'AMENDMENT',
  SIGNATURE = 'SIGNATURE',
  VETO = 'VETO',
  ENACTMENT = 'ENACTMENT'
} 